alpha: 1
batch_size: 512
data_path: ../datasets/
dataset: CIFAR10
epochs: 100
gpu: 0
inference_dataset: CIFAR10
input_shape: 32,32,3
learning_rate: 0.01
load_pretrained: 'no'
log_path: ./save
loss_type: ce
lp: 2
mode: shadow
model: resnet18
num_class: 10
num_workers: 10
optimizer: sgd
scheduler: cosine
seed: 0
series: 2
task: mia
tau: 1
temp: 1
training_type: Normal
