T_destination: ~T_destination
_backward_hooks: OrderedDict()
_buffers: OrderedDict()
_forward_hooks: OrderedDict()
_forward_pre_hooks: OrderedDict()
_is_full_backward_hook: None
_load_state_dict_post_hooks: OrderedDict()
_load_state_dict_pre_hooks: OrderedDict()
_modules: OrderedDict()
_non_persistent_buffers_set: set()
_parameters: OrderedDict()
_state_dict_hooks: OrderedDict()
_version: '1'
alpha: '1'
device: 'cuda : 0'
dump_patches: 'False'
k: '10'
q: '0.2'
reduction: mean
training: 'True'
